// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5hH7KCBMrsMxESe3VK7BHX3G3zSIiqMg',
    appId: '1:643768628872:web:01bbb6a78b2d69424c513d',
    messagingSenderId: '643768628872',
    projectId: 'some-db-addict',
    authDomain: 'some-db-addict.firebaseapp.com',
    storageBucket: 'some-db-addict.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3I1PcFc86Zx4TjxOuw3BSjOVyq2_Ook',
    appId: '1:643768628872:android:1b757019428946914c513d',
    messagingSenderId: '643768628872',
    projectId: 'some-db-addict',
    storageBucket: 'some-db-addict.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZovB7_S2lHSxQh1SMUtYRBTuCaIm7ad0',
    appId: '1:643768628872:ios:639d9bbe542350214c513d',
    messagingSenderId: '643768628872',
    projectId: 'some-db-addict',
    storageBucket: 'some-db-addict.firebasestorage.app',
    iosBundleId: 'com.example.deTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZovB7_S2lHSxQh1SMUtYRBTuCaIm7ad0',
    appId: '1:643768628872:ios:639d9bbe542350214c513d',
    messagingSenderId: '643768628872',
    projectId: 'some-db-addict',
    storageBucket: 'some-db-addict.firebasestorage.app',
    iosBundleId: 'com.example.deTalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5hH7KCBMrsMxESe3VK7BHX3G3zSIiqMg',
    appId: '1:643768628872:web:30cfe871e974e6e84c513d',
    messagingSenderId: '643768628872',
    projectId: 'some-db-addict',
    authDomain: 'some-db-addict.firebaseapp.com',
    storageBucket: 'some-db-addict.firebasestorage.app',
  );

}